### how to Load and use numpy

In [14]:
import numpy as np

#simple array
a = np.array([7, 8, 9, 10, 11])
print(a **2)

#Complex array
b = np.array([[25, 26, 27, 28], [40, 20, 30, 60]])

#print the info of the array
print(b.shape)

#Storing first column on the first row

new_column = b[0, :]
print(new_column)


[ 49  64  81 100 121]
(2, 4)
[25 26 27 28]


In [ ]:
#3D arrays

# declearing a varibale
height = [1.68, 2.68, 9.85]
weight = [82.25, 20.00, 40.36]
age = [25, 26, 40]

#coverting the three list into an array
np_3d = np.array([height, weight, age])
print(np_3d)

#Checking the info
print(np_3d.shape)


[[ 1.68  2.68  9.85]
 [82.25 20.   40.36]
 [25.   26.   40.  ]]
(3, 3)


2